// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpskcajfhmlcmeivgbjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc2tjYWpmaG1sY21laXZnYmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzQ5MjEsImV4cCI6MjA2MzQxMDkyMX0.PKm49ycsc5d2izweW0dJ6Sy-xc0HGdDE58EhrFUkumk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);